include(${CMAKE_SOURCE_DIR}/test/mcsvulkan/tool.cmake)
include(${CMAKE_SOURCE_DIR}/test/mcsvulkan/wsi.cmake)
include(${CMAKE_SOURCE_DIR}/test/mcsvulkan/macro.cmake)
include(${CMAKE_SOURCE_DIR}/test/mcsvulkan/vma.cmake)
include(${CMAKE_SOURCE_DIR}/test/mcsvulkan/integration.cmake)
include(${CMAKE_SOURCE_DIR}/test/mcsvulkan/glm.cmake)
include(${CMAKE_SOURCE_DIR}/test/mcsvulkan/type_traits.cmake)
include(${CMAKE_SOURCE_DIR}/test/mcsvulkan/conn.cmake)